// Product
export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
export const SELECT_PRODUCT = "SELECT_PRODUCT"

export const BUY_PRODUCT = "BUY_PRODUCT"
export const BUY_PRODUCT_FAILURE = "BUY_PRODUCT_FAILURE"

// Coin
export const FETCH_COINS = "FETCH_COINS"

// Balance
export const INCREMENT_BALANCE = "INCREMENT_BALANCE"
export const DECREMENT_BALANCE = "DECREMENT_BALANCE"